### ISSUE TITLE
Missing dependency doing setup.py

### ISSUE THREAD

**Issue by RJT1990** [paperswithcode/paperswithcode-client#2]
(pwc) rjt-mbp:paperswithcode-client rjt$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from paperswithcode import __version__
  File "/Users/rjt/Documents/software/paperswithcode-client/paperswithcode/__init__.py", line 3, in <module>
    from paperswithcode.client import PapersWithCodeClient
  File "/Users/rjt/Documents/software/paperswithcode-client/paperswithcode/client.py", line 5, in <module>
    from tea_client.http import HttpClient
ModuleNotFoundError: No module named 'tea_client'

**Comment by alefnula** [comment]
Fixed. Will be released in version 0.0.15.
